export type CityIconImagesType = {
  [key: string]: string[];
};

export const cityIconImages: CityIconImagesType = {
  "rio de janeiro": [],
  "buenos aires": [],
  cordoba: [],
  "la plata": [],
  lima: [],
  monterrey: [],
  montreal: [],
  "new york city": [],
  "san francisco": [],
  "são paulo": [],
  toronto: [],
  bangkok: [],
  "chiang mai": [],
  daegu: [],
  nanjing: [],
  saigon: [],
  singapore: [],
  yangon: [],
  auckland: [],
  melbourne: [],
  wellington: [],
  amsterdam: [],
  barcelona: [],
  cologne: [],
  copenhagen: [],
  geneva: [],
  lisbon: [],
  london: [],
  oslo: [],
  paris: [""],
  porto: [],
};
