export const managers = [
  { name: "Sébastien Vigny", city: "Geneva" },
  { name: "Vitaly Berg", city: "Oslo" },
  { name: "Benji Moreira", city: "Cordoba" },
  { name: "Alexandre Quach-Hiep", city: "Paris" },
  { name: "Hồ Liam", city: "Saigon" },
  { name: "Samantha Encalada Rafael", city: "Lima" },
  { name: "Martin Javier Monteoliva Ramos", city: "Cordoba" },
  { name: "Simon Potvin", city: "Yangon" },
  { name: "Pann Thitsar", city: "Yangon" },
  { name: "Zhang Laurel", city: "Nanjing" },
  { name: "Polina Feofanova", city: "Rio de Janeiro" },
  { name: "Mirjam Tanner", city: "La Plata" },
  { name: "Olivia Sumich", city: "Auckland" },
  { name: "Kelly Chan", city: "Singapore" },
  { name: "Victoria Galmarini", city: "Buenos Aires" },
  { name: "ibelitze zambrano", city: "Lima" },
  { name: "Meigh Banchanurat", city: "Bangkok" },
  { name: "Mai Tran", city: "Hanoi" },
  { name: "ANTONIO NETO", city: "São Paulo" },
  { name: "Mélissa Dauber", city: "Paris" },
  { name: "Girish Bhagat", city: "London" },
  { name: "Effie Bobae Kim", city: "Daegu" },
  { name: "Israel Almaraz", city: "San Francisco" },
  { name: "Amanda Torres", city: "Philadelphia" },
  { name: "Minske Moltzen", city: "Wellington" },
  { name: "Hazal Parmaksiz", city: "Cologne" },
  { name: "Edgar Vargas", city: "Monterrey" },
  { name: "Paula Costa", city: "Porto" },
  { name: "Gina Melchner", city: "Amsterdam" },
  { name: "Igor Knezic", city: "Toronto" },
  { name: "Tony Visicontti", city: "Toronto" },
  { name: "Senote Keriakes", city: "Melbourne" },
];
