export const managers = [
  // { name: "Sébastien Vigny", city: "Geneva" },
  // { name: "Vitaly Berg", city: "Oslo" },
  // { name: "Benji Moreira", city: "Cordoba" },
  // { name: "Alexandre Quach-Hiep", city: "Paris" },
  // { name: "Hồ Liam", city: "Saigon" },
  // { name: "Samantha Encalada Rafael", city: "Lima" },
  // { name: "Martin Javier Monteoliva Ramos", city: "Cordoba" },
  // { name: "Simon Potvin", city: "Yangon" },
  // { name: "Pann Thitsar", city: "Yangon" },
  // { name: "Zhang Laurel", city: "Nanjing" },
  // { name: "Polina Feofanova", city: "Rio de Janeiro" },
  // { name: "Mirjam Tanner", city: "La Plata" },
  // { name: "Olivia Sumich", city: "Auckland" },
  // { name: "Kelly Chan", city: "Singapore" },
  // { name: "Victoria Galmarini", city: "Buenos Aires" },
  // { name: "ibelitze zambrano", city: "Lima" },
  // { name: "Meigh Banchanurat", city: "Bangkok" },
  // { name: "Mai Tran", city: "Hanoi" },
  // { name: "ANTONIO NETO", city: "São Paulo" },
  // { name: "Mélissa Dauber", city: "Paris" },
  // { name: "Girish Bhagat", city: "London" },
  // { name: "Effie Bobae Kim", city: "Daegu" },
  // { name: "Israel Almaraz", city: "San Francisco" },
  // { name: "Amanda Torres", city: "Philadelphia" },
  // { name: "Minske Moltzen", city: "Wellington" },
  // { name: "Hazal Parmaksiz", city: "Cologne" },
  // { name: "Edgar Vargas", city: "Monterrey" },
  // { name: "Paula Costa", city: "Porto" },
  // { name: "Gina Melchner", city: "Amsterdam" },
  // { name: "Igor Knezic", city: "Toronto" },
  // { name: "Tony Visicontti", city: "Toronto" },
  // { name: "Senote Keriakes", city: "Melbourne" },
  { name: "John Doe", city: "Geneva" },
  { name: "Jane Smith", city: "Oslo" },
  { name: "Robert Johnson", city: "Cordoba" },
  { name: "Michael Williams", city: "Paris" },
  { name: "Sarah Brown", city: "Saigon" },
  { name: "David Jones", city: "Lima" },
  { name: "Emily Davis", city: "Cordoba" },
  { name: "James Miller", city: "Yangon" },
  { name: "Jessica Wilson", city: "Yangon" },
  { name: "Thomas Moore", city: "Nanjing" },
  { name: "Linda Taylor", city: "Rio de Janeiro" },
  { name: "Richard Anderson", city: "La Plata" },
  { name: "Patricia Thomas", city: "Auckland" },
  { name: "Christopher Jackson", city: "Singapore" },
  { name: "Elizabeth White", city: "Buenos Aires" },
  { name: "Daniel Harris", city: "Lima" },
  { name: "Megan Martin", city: "Bangkok" },
  { name: "Matthew Thompson", city: "Hanoi" },
  { name: "Lauren Garcia", city: "São Paulo" },
  { name: "Joseph Martinez", city: "Paris" },
  { name: "Grace Rodriguez", city: "London" },
  { name: "Andrew Lewis", city: "Daegu" },
  { name: "Hannah Lee", city: "San Francisco" },
  { name: "Anthony Walker", city: "Philadelphia" },
  { name: "Brianna Hall", city: "Wellington" },
  { name: "Samuel Allen", city: "Cologne" },
  { name: "Olivia Young", city: "Monterrey" },
  { name: "Nicholas Hernandez", city: "Porto" },
  { name: "Kylie King", city: "Amsterdam" },
  { name: "Ryan Wright", city: "Toronto" },
  { name: "Alexis Lopez", city: "Toronto" },
  { name: "William Hill", city: "Melbourne" },
];
